### ISSUE TITLE
crashes when trying to load a non-existing jsfx file

### ISSUE THREAD

**Issue by umlaeute** [asb2m10/jsusfx#1]
running the example patch, this crashes immediately if click on the ` [compile octaveup(` button while dsp is **on**.

system:
- Debian stretch/sid amd64
- Pd-0.47.0 from git
- jsusfx 0.2
- clang/clang++ 3.6.2-3

it does work however, if i compile the everything with *gcc* (Debian 5.3.1-9).

**Comment by asb2m10** [comment]
I forgot to initialize the return string on call for open_via_path. Fix committed in master.

Thanks for reporting.
