### ISSUE TITLE
runtime execstack detection

### ISSUE THREAD

**Issue by umlaeute** [asb2m10/jsusfx#10]
would it be possible to detect the usability of *native* x86 instructions on the stack at runtime (to prevent segfaults)?

**Comment by umlaeute** [comment]
and if it was possible, would it be possible to switch to the *portable* implementation if *native* cannot be used?

**Comment by asb2m10** [comment]
I've found a *clean* way to avoid the use of execstack; works out of the box on Linux and OS X.

Native should be as stable as the portable one, so I don't see a use case to support both mode in one binary. 

The build tough could be modified to check if php and nasm is installed. I'm not just ready "mentally" to add autoconf as a build tool.

**Comment by umlaeute** [comment]
:+1:
