### ISSUE TITLE
import statements

### ISSUE THREAD

**Issue by marcel303** [asb2m10/jsusfx#17]
Hey,

For some files to compile I need proper import statement support. I'd like to know your thoughts on this. :-)

Specifically, I'm trying to get some of the ATK for Reaper plugins to work,
https://github.com/ambisonictoolkit/atk-reaper

With the changes I already made, some of them are already working. But most of them will actually need the import statement to work. What are your thoughts on this? I can imagine there's a potential security risk with letting scripts access arbitrary files (how does Reaper deal with this.. ?). Other than this I think it should be feasible to add support with not a whole lot of changes. So perhaps an opt-in system where the user of the library specifies whether he/she wants import behavior to work or not could be a possible solution?

Cheers,
Marcel

**Comment by asb2m10** [comment]
Hi Marcel,

Yes, it is a good idea to implement this... To me, the import path could be platform dependent (for pd this is the pd path/on max, the max path), we could add an abstract member called resolvImport to the JsusFx object.

As for potential security risks... there is some, but I think Max/MSP with the JS object has the same potential risk and security is always about managing risk. 

Let me see if this can be implemented easily...

**Comment by marcel303** [comment]
Hey, ok, I will start implementing this. I like the idea of making it abstract, so the environment (Pd, Max, or some other environment) becomes responsible for managing security, and proving file access. Usually the environment also lets the user to set up search paths, which could be taken into consideration by the implementation.

I will first make an initial version, just to see how the script compiler expects to be fed the source code, and to see what's needed to make the ATK scripts work. Those scripts include a ton of code and import statements, so it's a good test to see if it works. :-)

**Comment by marcel303** [comment]
I made a new branch and pushed some changes to https://github.com/marcel303/jsusfx/tree/import-statements

With some work I managed to compile the 'DirectO' transform script of the ATK.

Things I needed to do were,
- Recursively traverse import statements. As soon as an import statement is encountered, it's traversed. All of the sections are parsed, and the source code gets appended to the current section.
- Adding a basic resolveImportFilename. For now it looks if the file exists in the current working directory, relative to the current working directory, or inside two hard-coded library paths (on my Mac). The abstract interface would hide all of this, and just check if the file exists or not. It would need to be aware of the current path though, to make relative file access work, so that should be part of the API (the path).
- Update the test so it changes the current working directory. This can be removed as soon as the abstract interface is there and implemented. Just a quick hack to make it work.
- Removing the body from two ATK scripts, which deal with files. Reascript/EEL defines a bunch of built-in functions which aren't available. See https://www.reaper.fm/sdk/reascript/reascripthelp.html. Obviously, it would be a lot of work to implement those, so I'm just working around this for now.
- I manually defined some gfx_*** functions inside the ATK. Same problem as above, but adding empty functions for these was the simplest solution. Otherwise I'd have to strip a _lot_ of code.

Here's the compiler output. Looking good. :-)

compile 1: ../../atk-reaper/plugins/FOA/Transform/DirectO
desc: ATK FOA Transform DirectO
spl0 --> 0.000000
spl1 --> 0.000000
srate --> 44100.000000
num_ch --> 2.000000
blockPerSample --> 64.000000
tempo --> 120.000000
play_state --> 1.000000
slider1 --> 0.000000 (Degree of transformatio)
kInvPi --> 0.318310
kRad2Deg --> 57.295780
kDeg2Rad --> 0.017453
kRad2Norm --> 0.318310
kSqrt2 --> 1.414214
kInvSqrt2 --> 0.707107
kHalfInvSqrt2 --> 0.353553
kSqrt3Div2 --> 0.866025
kSqrt3Div6 --> 0.288675
kSqrt6Div3 --> 0.816497
kRecSqrt6 --> 0.408248
kCos88 --> 0.034899
kNumLeds --> 19.000000
kDecibelsPerLed --> 3.000000
COOKDSP_VERSION --> 0.300000
ATK_VERSION --> 1.001000
initialised --> 1.000000
matrixDSP --> 1200.000000
matrixNewDSP --> 1220.000000
matrixInc --> 1240.000000
matrixDisplayPoints --> 1300.000000
matrixDisplayTransformed --> 1400.000000
matrixDisplayInterpreted --> 1500.000000
numDisplayedPoints --> 24.000000
mInteractionCircleRadius --> 11.000000
mPreviousMouseCap --> 0.000000
mClickingAtCircle --> 0.000000
mTransformAngle --> 0.000000
mNormTransformAngle --> 0.000000
i --> 0.000000
samplesblock --> 0.000000
inverseSamplesblock --> inf
ii --> 16.000000
wIn --> 0.000000
xIn --> 0.000000
yIn --> 0.000000
spl2 --> 0.000000
zIn --> 0.000000
spl3 --> 0.000000
Program ended with exit code: 0

**Comment by marcel303** [comment]
Latest push to the import statement branch includes a 'path library' interface and changes to the script compiler and test app.

The interface I came up with is this,

struct JsusFxPathLibrary {
	virtual bool resolveImportPath(const std::string &importPath, const std::string &parentPath, std::string &resolvedPath) {
		return false;
	}
	
	virtual std::istream* open(const std::string &path) {
		return nullptr;
	}
	
	virtual void close(std::istream *&stream) {
	}
};

The reason for making it a separate object is because I prefer to separate out file/io interfaces from the rest of the object.

The resolveImportPath implementation in jsusfx_test is really simple, but works well enough to work for the ATK.. and probably most other scripts you throw at it.
