### ISSUE TITLE
[oggread] in Pd-example patch

### ISSUE THREAD

**Issue by umlaeute** [asb2m10/jsusfx#2]
*oggread* is an external not available everywhere (esp, since Pd-extended is rather dead).
Also there is no *test.ogg* file.

Since the example works fine without any file-playback, i suggest to change the audio source to some vanilla objects (`[osc~]` and/or `[noise~]`)

**Comment by asb2m10** [comment]
That was for my "personal" tests... I add something more user friendly/pd-vanilla in the next commit

**Comment by umlaeute** [comment]
i figured.. but since this was the only test-file *I* could use, i though i'd report it.

thanks anyhow, for the (coming) fix.

**Comment by asb2m10** [comment]
The oggread~ is now removed from the test patch
