### ISSUE TITLE
build fails on 64 bit 

### ISSUE THREAD

**Issue by shreeswifty** [asb2m10/jsusfx#23]
Ubuntu 16LTS
i built first on 32bit and it built perfectly on 64 bit though i get 
maybe i am using wrong compiler
[shree@shree-linux2:~$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.10' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10) ]

Error i get when running make install in pd =

/home/shree/Documents/Pd/jsusfx/src/jsusfx.cpp: In member function ‘void JsusFxPathLibrary_Basic::addSearchPath(const string&)’:
/home/shree/Documents/Pd/jsusfx/src/jsusfx.cpp:337:12: error: ‘const string {aka const class std::__cxx11::basic_string<char>}’ has no member named ‘back’
  if ( path.back() == '/' || path.back() == '\\' )
            ^
/home/shree/Documents/Pd/jsusfx/src/jsusfx.cpp:337:34: error: ‘const string {aka const class std::__cxx11::basic_string<char>}’ has no member named ‘back’
  if ( path.back() == '/' || path.back() == '\\' )
                                  ^
/home/shree/Documents/Pd/jsusfx/src/jsusfx.cpp: In static member function ‘static bool JsusFxPathLibrary_Basic::fileExists(const string&)’:
/home/shree/Documents/Pd/jsusfx/src/jsusfx.cpp:344:27: error: no matching function for call to ‘std::basic_ifstream<char>::basic_ifstream(const string&)’
  std::ifstream is(filename);
                           ^
In file included from /home/shree/Documents/Pd/jsusfx/src/jsusfx.cpp:46:0:
/usr/include/c++/5/fstream:495:7: note: candidate: std::basic_ifstream<_CharT, _Traits>::basic_ifstream(const char*, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; std::ios_base::openmode = std::_Ios_Openmode]
       basic_ifstream(const char* __s, ios_base::openmode __mode = ios_base::in)
       ^
/usr/include/c++/5/fstream:495:7: note:   no known conversion for argument 1 from ‘const string {aka const std::__cxx11::basic_string<char>}’ to ‘const char*’
/usr/include/c++/5/fstream:481:7: note: candidate: std::basic_ifstream<_CharT, _Traits>::basic_ifstream() [with _CharT = char; _Traits = std::char_traits<char>]
       basic_ifstream() : __istream_type(), _M_filebuf()
       ^
/usr/include/c++/5/fstream:481:7: note:   candidate expects 0 arguments, 1 provided
/usr/include/c++/5/fstream:455:11: note: candidate: std::basic_ifstream<char>::basic_ifstream(const std::basic_ifstream<char>&)
     class basic_ifstream : public basic_istream<_CharT, _Traits>
           ^
/usr/include/c++/5/fstream:455:11: note:   no known conversion for argument 1 from ‘const string {aka const std::__cxx11::basic_string<char>}’ to ‘const std::basic_ifstream<char>&’
/home/shree/Documents/Pd/jsusfx/src/jsusfx.cpp: In member function ‘virtual bool JsusFxPathLibrary_Basic::resolveImportPath(const string&, const string&, std::__cxx11::string&)’:
/home/shree/Documents/Pd/jsusfx/src/jsusfx.cpp:358:35: warning: range-based ‘for’ loops only available with -std=c++11 or -std=gnu++11
  for ( std::string & searchPath : searchPaths ) {
                                   ^
/home/shree/Documents/Pd/jsusfx/src/jsusfx.cpp: In member function ‘virtual std::istream* JsusFxPathLibrary_Basic::open(const string&)’:
/home/shree/Documents/Pd/jsusfx/src/jsusfx.cpp:377:48: error: no matching function for call to ‘std::basic_ifstream<char>::basic_ifstream(const string&)’
  std::ifstream *stream = new std::ifstream(path);
                                                ^
In file included from /home/shree/Documents/Pd/jsusfx/src/jsusfx.cpp:46:0:
/usr/include/c++/5/fstream:495:7: note: candidate: std::basic_ifstream<_CharT, _Traits>::basic_ifstream(const char*, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; std::ios_base::openmode = std::_Ios_Openmode]
       basic_ifstream(const char* __s, ios_base::openmode __mode = ios_base::in)
       ^
/usr/include/c++/5/fstream:495:7: note:   no known conversion for argument 1 from ‘const string {aka const std::__cxx11::basic_string<char>}’ to ‘const char*’
/usr/include/c++/5/fstream:481:7: note: candidate: std::basic_ifstream<_CharT, _Traits>::basic_ifstream() [with _CharT = char; _Traits = std::char_traits<char>]
       basic_ifstream() : __istream_type(), _M_filebuf()
       ^
/usr/include/c++/5/fstream:481:7: note:   candidate expects 0 arguments, 1 provided
/usr/include/c++/5/fstream:455:11: note: candidate: std::basic_ifstream<char>::basic_ifstream(const std::basic_ifstream<char>&)
     class basic_ifstream : public basic_istream<_CharT, _Traits>
           ^
/usr/include/c++/5/fstream:455:11: note:   no known conversion for argument 1 from ‘const string {aka const std::__cxx11::basic_string<char>}’ to ‘const std::basic_ifstream<char>&’
/home/shree/Documents/Pd/jsusfx/src/CMakeFiles/jsusfx.dir/build.make:66: recipe for target '/home/shree/Documents/Pd/jsusfx/src/CMakeFiles/jsusfx.dir/jsusfx.cpp.o' failed
make[2]: *** [/home/shree/Documents/Pd/jsusfx/src/CMakeFiles/jsusfx.dir/jsusfx.cpp.o] Error 1
CMakeFiles/Makefile2:122: recipe for target '/home/shree/Documents/Pd/jsusfx/src/CMakeFiles/jsusfx.dir/all' failed
make[1]: *** [/home/shree/Documents/Pd/jsusfx/src/CMakeFiles/jsusfx.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by asb2m10** [comment]
Hmmm... C++11 extension doesn't seems to be enable.

Can you add `set (CMAKE_CXX_STANDARD 11)` in CMakeLists.txt so cmake will force the compiler to support C++11 ?

**Comment by shreeswifty** [comment]
yup! that did the trick, thanks!

**Comment by shreeswifty** [comment]
hey found another error i cant seem to get past this time, found my solution for the other error again but i get this
/Users/shree/Documents/Pd/jsusfx/pd/jsusfx_pd.cpp:153:34: error: read-only variable is not assignable
                midi[midiSize++] = midiPreStream[i];
