### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by Rcomian** [asb2m10/jsusfx#25]
Are there any instructions on how to get this building properly on windows? What tools are needed, the workflow, etc.

Also, is there anyway of getting the resulting library to link with a mingw binary?

**Comment by asb2m10** [comment]
jsusfx uses CMake, for now this should work: 
https://github.com/tudelft3d/masbcpp/wiki/Building-on-Windows-with-CMake-and-MinGW

Let me know if this works and I'll add it to the documentation.
