### ISSUE TITLE
Trying to build on mojave 64

### ISSUE THREAD

**Issue by shreeswifty** [asb2m10/jsusfx#31]
hey found another error i cant seem to get past this time, found my solution for the other error again but i get this
/Users/shree/Documents/Pd/jsusfx/pd/jsusfx_pd.cpp:153:34: error: read-only variable is not assignable
midi[midiSize++] = midiPreStream[i];

Any ideas?

**Comment by asb2m10** [comment]
Yes, compilers get more clever about anonymous pointers...

I did a fix for this, just pull the new version and tell me if it works.
