### ISSUE TITLE
Pd: "midi" message multiply defined

### ISSUE THREAD

**Issue by umlaeute** [asb2m10/jsusfx#33]
there's some fishy code going on in the Pd-backend, where the selector `midi` is assigned to multiple callbacks:

https://github.com/asb2m10/jsusfx/blob/aa6da16fa58bffea6602a2cf6dd5237c88d28452/pd/jsusfx_pd.cpp#L591-L592

This is not supported by Pd: a selector can only be bound to a single `classmethod`.
Since an `A_GIMME` is a superset of an `A_FLOAT`, you could simply dispatch a 1-floatatom-list to `jsusfx_midi` from `jsusfx_list`. However, since `jsusfx_list` is already doing that, you can simply remove the `jsusfx_midi` callback altogether.

Furthermore the midi-methods for `[jsfx~]` seem to be setup wrongly altogether:
https://github.com/asb2m10/jsusfx/blob/aa6da16fa58bffea6602a2cf6dd5237c88d28452/pd/jsusfx_pd.cpp#L602-L605
I guess the **`jsusfx_class`** is just a typo and should read **`jsfx_class`** instead. (and again the callback for `jsusfx_midi` should be removed)

**Comment by asb2m10** [comment]
Thanks for reporting this, didn't know that A_GIMME was superseded by A_FLOAT. It is now fixed.

**Comment by umlaeute** [comment]
it's not that `A_GIMME` is superseded by `A_FLOAT`, it's rather that a recent call to `class_addmethod` overrides any previous call that uses the same selector (and issues as high-verbose error message).

anyhow, thanks for fixing.
